name: Update ical data
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  update:
    name: Update ical data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: make
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          clean: false
      - run: |
          git add nijisanji-ics
          git commit -m 'update by github actions'
      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
